port: "8080"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "DigQueueDB"
  sslmode: "disable"

token:
  accessTokenTTL: 900 # 900s = 15m
  refreshTokenTTL: 2592000 # 2592000s = 30 days